spring:
  r2dbc:
    username: user
    password: password
    url: r2dbc:postgresql://localhost:5432/bookdb_order
    pool:
      max-create-connection-time: 2s
      initial-size: 5
      max-size: 10
  lifecycle:
    timeout-per-shutdown-phase: 15s
  application:
    name: order-service
  flyway:
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: jdbc:postgresql://localhost:5432/bookdb_order

book:
  catalog-service-uri: "http://localhost:9001"

server:
  port: 9002
  shutdown: graceful
  netty:
    connection-timeout: 2s
    idle-timeout: 15s